# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - electronicnetdev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '4.8.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1            
      
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: Create Build Directory
        run: mkdir _build
        
      - name: Restore Packages
        run: nuget restore SolutionElectronicNet/SolutionElectronicNet.sln

      - name: Build Solution
        run: |
             msbuild.exe SolutionElectronicNet/SolutionElectronicNet.sln /p:platform="Any CPU" /p:configuration="Release"


      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: SolutionElectronicNet
          path: "./_build"

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CD93CA484B244698B541F8A2CB842017 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_379759C3C22E4E93903BF8CCA30044DE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8BE94210977A43AF9F67372EDB1826FB }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'electronicnetdev'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          
